/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
    'services-page': ServicesPage;
    'fund-screener-page': FundScreenerPage;
    'goal-planner-page': GoalPlannerPage;
    'sip-page': SipPage;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'fund-screener-page': FundScreenerPageSelect<false> | FundScreenerPageSelect<true>;
    'goal-planner-page': GoalPlannerPageSelect<false> | GoalPlannerPageSelect<true>;
    'sip-page': SipPageSelect<false> | SipPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  hero: {
    badge: string;
    heading: string;
    highlightedText: string;
    description: string;
    primaryButtonText: string;
    primaryButtonHref: string;
    secondaryButtonText: string;
    secondaryButtonHref: string;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    formTitle: string;
    formButtonText: string;
  };
  aboutUs: {
    badge: string;
    heading: string;
    description1: string;
    description2: string;
    buttonText: string;
    buttonHref: string;
    features?:
      | {
          iconName: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  financialResources: {
    heading: string;
    description: string;
    items?:
      | {
          /**
           * Icon name like Calculator, Target, BarChart3, etc.
           */
          iconName: string;
          title: string;
          description: string;
          href: string;
          buttonText: string;
          id?: string | null;
        }[]
      | null;
  };
  conversionBanner: {
    badge: string;
    heading: string;
    description: string;
    primaryButtonText: string;
    primaryButtonHref: string;
    secondaryButtonText: string;
    secondaryButtonHref: string;
    contactInfo?:
      | {
          iconName: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  hero: {
    badge: string;
    heading: string;
    highlightedText: string;
    description: string;
    stats?:
      | {
          value: string;
          label: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  story: {
    badge: string;
    heading: string;
    description1: string;
    description2: string;
    credentials?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  missionVision: {
    missionBadge: string;
    missionTitle: string;
    missionDescription: string;
    visionBadge: string;
    visionTitle: string;
    visionDescription: string;
  };
  coreValues: {
    badge: string;
    heading: string;
    description: string;
    items?:
      | {
          iconName: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    heading: string;
    description: string;
    buttonText: string;
    buttonHref: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  hero: {
    badge: string;
    heading: string;
    highlightedText: string;
    description: string;
  };
  contactDetails: {
    heading: string;
    description: string;
    methods?:
      | {
          id: string;
          iconName: string;
          title: string;
          value: string;
          href: string;
          linkText: string;
        }[]
      | null;
  };
  map: {
    heading: string;
    address: string;
    embedUrl: string;
    buttonText: string;
    buttonHref: string;
  };
  form: {
    title: string;
    buttonText: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  hero: {
    badge: string;
    heading: string;
    highlightedText: string;
    description: string;
  };
  services?:
    | {
        id: string;
        number: string;
        iconName: string;
        title: string;
        description: string;
        features?:
          | {
              feature: string;
              id?: string | null;
            }[]
          | null;
        tags?:
          | {
              tag: string;
              id?: string | null;
            }[]
          | null;
      }[]
    | null;
  conversionBanner: {
    badge: string;
    heading: string;
    description: string;
    primaryButtonText: string;
    primaryButtonHref: string;
    secondaryButtonText: string;
    secondaryButtonHref: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fund-screener-page".
 */
export interface FundScreenerPage {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  hero: {
    badge: string;
    heading: string;
    description: string;
  };
  filters: {
    title: string;
    description: string;
    searchLabel: string;
    searchPlaceholder: string;
    categoryLabel: string;
    categoryPlaceholder: string;
    allCategories: string;
    fundHouseLabel: string;
    fundHousePlaceholder: string;
    allFundHouses: string;
    applyButton: string;
    resetButton: string;
  };
  results: {
    title: string;
    loadingText: string;
    errorTitle: string;
    errorButton: string;
    prevButton: string;
    nextButton: string;
    noResults: string;
    investButton: string;
    prevPageButton: string;
    nextPageButton: string;
  };
  disclaimer: {
    text: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "goal-planner-page".
 */
export interface GoalPlannerPage {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  hero: {
    badge: string;
    heading: string;
    description: string;
  };
  goalDetails: {
    title: string;
    description: string;
    goalTypeLabel: string;
    goalAmountLabel: string;
    timeToGoalLabel: string;
    goalTypes?:
      | {
          id: string;
          name: string;
          icon: string;
        }[]
      | null;
  };
  investmentParameters: {
    title: string;
    description: string;
    currentSavingsLabel: string;
    expectedReturnLabel: string;
    inflationLabel: string;
  };
  goalAnalysis: {
    title: string;
    goalAmountLabel: string;
    inflationAdjustedGoalLabel: string;
    monthlyInvestmentNeededLabel: string;
  };
  investmentTimeline: {
    title: string;
    currentAgeLabel: string;
    goalAchievementAgeLabel: string;
    investmentPeriodLabel: string;
    totalMonthlyInvestmentsLabel: string;
  };
  actions: {
    primaryButtonText: string;
    primaryButtonHref: string;
    secondaryButtonText: string;
    secondaryButtonHref: string;
  };
  tips: {
    title: string;
    items?:
      | {
          heading: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sip-page".
 */
export interface SipPage {
  id: number;
  seo: {
    title: string;
    description: string;
  };
  hero: {
    badge: string;
    heading: string;
    description: string;
  };
  investmentDetails: {
    title: string;
    description: string;
    monthlyInvestmentLabel: string;
    expectedReturnLabel: string;
    timePeriodLabel: string;
  };
  investmentResults: {
    title: string;
    totalInvestmentLabel: string;
    estimatedReturnsLabel: string;
    totalValueLabel: string;
  };
  visualRepresentation: {
    title: string;
    principalAmountLabel: string;
    returnsLabel: string;
  };
  actions: {
    primaryButtonText: string;
    primaryButtonHref: string;
    secondaryButtonText: string;
    secondaryButtonHref: string;
  };
  disclaimer: {
    text: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        badge?: T;
        heading?: T;
        highlightedText?: T;
        description?: T;
        primaryButtonText?: T;
        primaryButtonHref?: T;
        secondaryButtonText?: T;
        secondaryButtonHref?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        formTitle?: T;
        formButtonText?: T;
      };
  aboutUs?:
    | T
    | {
        badge?: T;
        heading?: T;
        description1?: T;
        description2?: T;
        buttonText?: T;
        buttonHref?: T;
        features?:
          | T
          | {
              iconName?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  financialResources?:
    | T
    | {
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              iconName?: T;
              title?: T;
              description?: T;
              href?: T;
              buttonText?: T;
              id?: T;
            };
      };
  conversionBanner?:
    | T
    | {
        badge?: T;
        heading?: T;
        description?: T;
        primaryButtonText?: T;
        primaryButtonHref?: T;
        secondaryButtonText?: T;
        secondaryButtonHref?: T;
        contactInfo?:
          | T
          | {
              iconName?: T;
              text?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        badge?: T;
        heading?: T;
        highlightedText?: T;
        description?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              description?: T;
              id?: T;
            };
      };
  story?:
    | T
    | {
        badge?: T;
        heading?: T;
        description1?: T;
        description2?: T;
        credentials?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  missionVision?:
    | T
    | {
        missionBadge?: T;
        missionTitle?: T;
        missionDescription?: T;
        visionBadge?: T;
        visionTitle?: T;
        visionDescription?: T;
      };
  coreValues?:
    | T
    | {
        badge?: T;
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              iconName?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        heading?: T;
        description?: T;
        buttonText?: T;
        buttonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        badge?: T;
        heading?: T;
        highlightedText?: T;
        description?: T;
      };
  contactDetails?:
    | T
    | {
        heading?: T;
        description?: T;
        methods?:
          | T
          | {
              id?: T;
              iconName?: T;
              title?: T;
              value?: T;
              href?: T;
              linkText?: T;
            };
      };
  map?:
    | T
    | {
        heading?: T;
        address?: T;
        embedUrl?: T;
        buttonText?: T;
        buttonHref?: T;
      };
  form?:
    | T
    | {
        title?: T;
        buttonText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        badge?: T;
        heading?: T;
        highlightedText?: T;
        description?: T;
      };
  services?:
    | T
    | {
        id?: T;
        number?: T;
        iconName?: T;
        title?: T;
        description?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        tags?:
          | T
          | {
              tag?: T;
              id?: T;
            };
      };
  conversionBanner?:
    | T
    | {
        badge?: T;
        heading?: T;
        description?: T;
        primaryButtonText?: T;
        primaryButtonHref?: T;
        secondaryButtonText?: T;
        secondaryButtonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fund-screener-page_select".
 */
export interface FundScreenerPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        badge?: T;
        heading?: T;
        description?: T;
      };
  filters?:
    | T
    | {
        title?: T;
        description?: T;
        searchLabel?: T;
        searchPlaceholder?: T;
        categoryLabel?: T;
        categoryPlaceholder?: T;
        allCategories?: T;
        fundHouseLabel?: T;
        fundHousePlaceholder?: T;
        allFundHouses?: T;
        applyButton?: T;
        resetButton?: T;
      };
  results?:
    | T
    | {
        title?: T;
        loadingText?: T;
        errorTitle?: T;
        errorButton?: T;
        prevButton?: T;
        nextButton?: T;
        noResults?: T;
        investButton?: T;
        prevPageButton?: T;
        nextPageButton?: T;
      };
  disclaimer?:
    | T
    | {
        text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "goal-planner-page_select".
 */
export interface GoalPlannerPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        badge?: T;
        heading?: T;
        description?: T;
      };
  goalDetails?:
    | T
    | {
        title?: T;
        description?: T;
        goalTypeLabel?: T;
        goalAmountLabel?: T;
        timeToGoalLabel?: T;
        goalTypes?:
          | T
          | {
              id?: T;
              name?: T;
              icon?: T;
            };
      };
  investmentParameters?:
    | T
    | {
        title?: T;
        description?: T;
        currentSavingsLabel?: T;
        expectedReturnLabel?: T;
        inflationLabel?: T;
      };
  goalAnalysis?:
    | T
    | {
        title?: T;
        goalAmountLabel?: T;
        inflationAdjustedGoalLabel?: T;
        monthlyInvestmentNeededLabel?: T;
      };
  investmentTimeline?:
    | T
    | {
        title?: T;
        currentAgeLabel?: T;
        goalAchievementAgeLabel?: T;
        investmentPeriodLabel?: T;
        totalMonthlyInvestmentsLabel?: T;
      };
  actions?:
    | T
    | {
        primaryButtonText?: T;
        primaryButtonHref?: T;
        secondaryButtonText?: T;
        secondaryButtonHref?: T;
      };
  tips?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              heading?: T;
              description?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sip-page_select".
 */
export interface SipPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        badge?: T;
        heading?: T;
        description?: T;
      };
  investmentDetails?:
    | T
    | {
        title?: T;
        description?: T;
        monthlyInvestmentLabel?: T;
        expectedReturnLabel?: T;
        timePeriodLabel?: T;
      };
  investmentResults?:
    | T
    | {
        title?: T;
        totalInvestmentLabel?: T;
        estimatedReturnsLabel?: T;
        totalValueLabel?: T;
      };
  visualRepresentation?:
    | T
    | {
        title?: T;
        principalAmountLabel?: T;
        returnsLabel?: T;
      };
  actions?:
    | T
    | {
        primaryButtonText?: T;
        primaryButtonHref?: T;
        secondaryButtonText?: T;
        secondaryButtonHref?: T;
      };
  disclaimer?:
    | T
    | {
        text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}